# See: https://getsentry.github.io/symbolicator/#configuration
cache_dir: "/data"
bind: "0.0.0.0:3021"
logging:
  level: "info"
metrics:
  statsd: null
sentry_dsn: null # TODO: Automatically fill this with the internal project DSN
